- name: Copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: get the entries count
  ansible.builtin.command: mongo --host mongodb.daws77s.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: entries_count
  when: component == "catalogue"

- name: get the entries count
  ansible.builtin.command: mongo --host mongodb.daws77s.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: entries_count
  when: component == "user"

# - name: print the count
#   ansible.builtin.debug:
#     msg: "product count: {{product_count}}"

- name: "load {{component}} data"
  ansible.builtin.command: "mongo --host mongodb.daws77s.online < /app/schema/{{component}}.js" 
  when: entries_count.stdout == "0" # keep double quotes
